### ISSUE TITLE
CPU use of threads doesn't make sense

### ISSUE THREAD

**Issue by madsciencetist** [shield-ai/sys_stats#6]
The cpu usage of a process' threads should be less than or equal to the cpu usage of the process, no? Here is a sample from a log:
```
- 
  pid: 17057
  percent_cpu: 92.0
  percent_memory: 0.705975532532
  name: "rosmaster"
  args: "/usr/bin/python /opt/ros/kinetic/bin/rosmaster --core -p 11311 -w 3 __log:=/home/shield/.ros/log/be66f0b6-0d6e-11e8-92bc-7a1d3ef0d47f/master.log"
  threads: 
    - 
      tid: 17060
      cpu_use: 92.0
      thread_name: "rosmaster"
    - 
      tid: 17061
      cpu_use: 92.0
      thread_name: "rosmaster"
    - 
      tid: 17062
      cpu_use: 92.0
      thread_name: "rosmaster"
    - 
      tid: 17063
      cpu_use: 92.0
      thread_name: "rosmaster"
    - 
      tid: 19401
      cpu_use: 318.0
      thread_name: "rosmaster"
    - 
      tid: 19402
      cpu_use: 318.0
      thread_name: "rosmaster"
    - 
      tid: 19403
      cpu_use: 318.0
      thread_name: "rosmaster"
```
